apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: eu-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 3
    volumeSize: 40
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key