apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sampleapp
  name: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - image: nginx
        name: sampleapp